# Python Basics

- This notebook contains a very accelerated summary of the basics of python. If this is challenging, please refer to the textbook sections.
- Being able to successfully run this also means you have a working Python environment! You now have installed everything you need to run this course.


## Python Basics

In [1]:
# Comments: The hashtag makes the rest of the line a comment. The more programming you do, the more you focus on making good comments.
# Jupyter lets you write formatted text, but you'll still want to put comments in the raw python.

# Assign some text (a string) to a variable
some_text = 'This is the text.'

# Assign some numbers to variables
a = 5  # Here, we implicitly told python that a is an integer
b = 4.6  # Here, we told python that b is a floating point number (a decimal)

- Even though nothing is outputted above, our Python "Kernel" has the values to each variable stored for later use.

### Important note: Python is not a "typed" language

- Notice that above, we added an integer and the float (a floating point number, i.e., one with a decimal point). Python "smartly" redefines variables so that they work together.

- This is different from other languages which require you to manually manage the "types" of your variables.

In [2]:
# Python as a calculator. 
sum_of_two_numbers = a + b

# Printing output to the console
print('Our output was', sum_of_two_numbers)

Our output was 9.6


- In the above, you'll notice the result was a float.
- If needed, you can demand that python specify something as a certain type, as below.

In [3]:
sum_as_int = int(sum_of_two_numbers)
sum_as_int_back_to_float = float(sum_as_int)

print('We lost some precision in this operation:', sum_as_int_back_to_float)

We lost some precision in this operation: 9.0


## Other python types

In [4]:
# Reminder, this assumes you have setup an envioronment with conda using:
list_1 = [4, 5, 6]
print('list_1', list_1)


list_1 [4, 5, 6]


In [5]:
# You can embed lists in lists in lists, etc.
list_2 = [[5, 3, 5], [6, 6, 5]]
print(list_2)


[[5, 3, 5], [6, 6, 5]]


In [6]:
# Dictionaries
dictionary_1 = {23: "Favorite number", 24: "Second favorite number"}
print('dictionary_1', dictionary_1)

# Here is a multi line string: (also discusses improved capabilities of an IDE editor)

things_you_can_do_in_vs_code_that_you_cant_do_without_an_ide = """
1.) Move back and forth in your history of cursor positions (using your mouse forward and back buttons)
2.) Edit on multiple lines at the same time (hold alt and click new spots)
3.) Smartly paste DIFFERENT values
4.) Duplicate lines (ctrl-d)
5.) Introspection (e.g., jump between function definition and usages)
6.) Debugging (Interactively walk through your code one line at a time)
7.) Profiling your code (see which lines take the most time to compute.)
8.) Keep track of a history of copy-paste items and paste from past copies. (ctrl-shift-v)
"""


dictionary_1 {23: 'Favorite number', 24: 'Second favorite number'}


## Looping

In [7]:


small_range = range(0, 10)
print('small_range:', small_range)

small_range_as_list = list(range(0, 10))
print('small_range_as_list:', small_range_as_list)

# Here is a for loop. Also note that python EXPLICITLY USES TAB-LEVEL to denote nested things.
# I.e., the inner part of the loop is tabbed 1 level up. Python does not use { like  R.
# I LOVE this notation and it's a big part of why python is so pretty and readable.
sum = 0 # Set the initial variable values
num = 0
sum_with_some = 0
for i in range(100, 136, 3):
    sum = sum + i
    num = num + 1

    # loop within a loop
    for j in range(200, 205):
        sum_with_some = sum + j

mean = sum / num
print('mean', mean)


small_range: range(0, 10)
small_range_as_list: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
mean 116.5



## Defining functions

In [8]:
# Functions
def my_function(input_parameter_1, input_parameter_2):
    product = input_parameter_1 * input_parameter_2
    return product

# Use the function
value_returned = my_function(2, 7)
print(value_returned)

14


In [9]:
# In-class exercise workspace

## Importing packages

In [10]:

# Built-in packages via the Python Standard Library
import math
import os, sys, time, random

# Using imported modules
number_rounded_down = math.floor(sum_of_two_numbers)
print(number_rounded_down)


9


## Using packages from elsewhere

When we used Mambaforge, we installed a ton of packages. These were not "built-in" to python like the ones above. Here we will import them into our notebook to use.

This will also illustrate the use of numpy. We'll use it so much we us the ```as``` code to name it something shorter.

In [11]:
import numpy as np # The as just defines a shorter name

# Create an 2 by 3 array of integers
small_array = np.array([[5, 3, 5], [6, 6, 5]])

print('Here\'s a small numpy array\n', small_array)

# Sidenote: from above backspace \ put in front of a character is the
# "escapce character," which makes python interpret the next thing as a string or special text operator. \n makes a line break

Here's a small numpy array
 [[5 3 5]
 [6 6 5]]


## Discussion point

The array above looks identical to the nested lists we made. It IS NOT! It is a numpy array that is ridiculously fast and can scale up to massive, massive data questions. The optional reading for today (Harris et al. 2020, Nature) discusses how these arrays have formed the backbone of modern scientific computing.

In [12]:
low = 3
high = 8
shape = (1000, 1000)

smallish_random_array = np.random.randint(low, high, shape)

print('Here\'s a slightly larger numpy array\n', smallish_random_array)


Here's a slightly larger numpy array
 [[4 7 3 ... 3 6 6]
 [7 6 4 ... 4 7 7]
 [5 6 3 ... 5 6 3]
 ...
 [4 3 7 ... 4 3 3]
 [7 4 4 ... 3 6 6]
 [4 5 4 ... 4 3 5]]


## In-class exercise 2.1 

Participation points note! I will call on a random table to show me their answer via their table's monitor.

Make a function that returns the square of a number. Combine the function  with a loop to calculate the Sum of Squared Numbers from 1 to 100.

HINT, ** is the exponent operator in python.

BONUS: Make sure you're actually right by inserting a print statement in each step.

BONUS-bonus: Store each stage of the results in a list using 
```your_list = []``` and ```your_list.append(thing_to_add_to_your_list)```